name: dependency_injection_flutter
description: dependency injection for flutter. inject factories or singletons. Easy to develop, easy to test.
version: 2.0.0
repository: https://github.com/flutterbrazil/dependency_injection_flutter
homepage: https://github.com/flutterbrazil/dependency_injection_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  effective_dart: ^1.3.1
  test: any
